version: '3'
services:
  forge:
    build:
      context: ./server
    image: eyedevelop/forge
    container_name: mcforge
    volumes:
      - "./vol/server:/server"
    restart: "no"
    environment:
      - PUID=1000
      - PGID=1000
      - FORGE_VERSION=1.16.4-35.1.0
      - MEMORY_USAGE=1G
